sudo: false
language: python
python:
  - "2.7"
  - "pypy"
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  # so that we can use conda to get scipy and bioconda to get bowtie
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
      export PATH="$HOME/miniconda/bin:$PATH";
    else
      export PATH="$PATH:$HOME/miniconda/bin";
    fi
  - conda update --yes conda
  - conda config --add channels r
  - conda config --add channels bioconda
  # debug message to diagnose issues with system python version
  - which python
  - python -c "import sys; print(sys.version.lower())"
  - wget ftp://igenome:G3nom3s4u@ussd-ftp.illumina.com/Drosophila_melanogaster/UCSC/dm6/Drosophila_melanogaster_UCSC_dm6.tar.gz
  - tar xf Drosophila_melanogaster_UCSC_dm6.tar.gz
  - ls Drosophila_melanogaster/UCSC/dm6/Sequence/BowtieIndex/
  - ls Drosophila_melanogaster/UCSC/dm6/Sequence/Bowtie2Index/
  - rm -rf Drosophila_melanogaster/UCSC/dm6/Annotation
  - for sd in BWAIndex AbundantSequences Chromosomes ; do rm -rf Drosophila_melanogaster/UCSC/dm6/Sequence/$sd ; done
  - wget http://verve.webfactional.com/mirror/linux/bedGraphToBigWig
  - chmod a+x bedGraphToBigWig
  - export PATH="$PATH:"`pwd`
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
      conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy weave;
    fi
  - conda install --yes bowtie bowtie2=2.2.5 samtools bedtools ucsc-bigwigtobedgraph
  - which bowtie
  - bowtie --version
  - which bowtie2
  - bowtie2 --version
script:
  - make
  - df -h
  - mkdir -p $HOME/railtemp
  - TMPDIR="$HOME/railtemp" python tests/line.py --bowtie-idx Drosophila_melanogaster/UCSC/dm6/Sequence/BowtieIndex/genome --bowtie2-idx Drosophila_melanogaster/UCSC/dm6/Sequence/Bowtie2Index/genome --genome Drosophila_melanogaster/UCSC/dm6/Sequence/WholeGenomeFasta/genome.fa --manifest ex/dm3_example.manifest
after_failure:
  - df -h
notifications:
  slack:
    rooms:
      secure: HiJEsOpApAMu+lev2n/vf71hGF3xC7PVtAz9OiSf0FCP6iwKyPT7FlpIB8v7av+mTR8M4/oAIT3kDQCt+YV1RvAoAQV5Z9wLJNPLTotVq+/L8K1nN2UrDFacNmTMZZoXIJN8Tf0vXB/jK6iE7BFcjU6Y7z0M0d6SJLisZpl8hcw=
